nethserver-mysql-migrate: revert to previous commit. Fix for migration is now in nethserver-base. Refs #1794

diff --git a/root/etc/e-smith/events/actions/nethserver-mysql-migrate b/root/etc/e-smith/events/actions/nethserver-mysql-migrate
--- a/root/etc/e-smith/events/actions/nethserver-mysql-migrate
+++ b/root/etc/e-smith/events/actions/nethserver-mysql-migrate
@@ -40,12 +40,8 @@ fi
 
 mysqlPassFile="$sourceDir/$mysqlPassFile"
 if [ ! -f "$mysqlPassFile" ]; then
-    #check if password file is already migrated
-    mysqlPassFile='/root/.my.cnf'
-    if [ ! -f "$mysqlPassFile" ]; then
-        echo "Could not find MySQL password file: $mysqlPassFile";
-        exit 1
-    fi
+    echo "Could not find MySQL password file: $mysqlPassFile";
+    exit 1
 fi
 
 status=$(/sbin/e-smith/config getprop mysqld status)
